# Refer to https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jochen Wurstbauer
title_separator: "|"
name: Jochen Wurstbauer
email:
description: >- # this means to ignore newlines until "baseurl:"
  Jochen Wurstbauer is a financial services professional with a 
  passion for Payments and Core Banking. He has 15+ years of 
  experience as a Business & IT-Consultant and Technical Product
  Owner with a proven track record of delivering large, complex 
  programs for established market leaders as well as Fintechs.
logo: "/assets/images/logo.png"
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Default site author
author:
  name   : "Jochen Wurstbauer"
  avatar : "/assets/images/avatar-jochen.jpg"
  bio    : "ISO 20022 Payments and Core Banking Enthusiast."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jochen-wb.github.io"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jochenwurstbauer"
    - label: "Xing"
      icon: "fab fa-fw fa-xing-square"
      url: "https://www.xing.com/profile/Jochen_Wurstbauer/"

# Footer settings
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jochenwurstbauer"
    - label: "Xing"
      icon: "fab fa-fw fa-xing-square"
      url: "https://www.xing.com/profile/Jochen_Wurstbauer/"

# Front Matter defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
